version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-ai-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MODEL_NAME=${MODEL_NAME:-gemini-1.5-flash}
      - BOT_NAME=${BOT_NAME:-WhatsApp AI Bot dengan Kecerdasan Emosional}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT}
    volumes:
      - ./data:/app/.wwebjs_auth
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:
  logs: